define("components/antd/index.js",function(require, exports, module) {
"use strict";
require("./style/index.css");
const index_1 = require("../button/index");
exports.Button = index_1.default;
let DatePicker = require('antd/lib/date-picker/index');
exports.DatePicker = DatePicker;
let Dropdown = require('antd/lib/dropdown/index');
exports.Dropdown = Dropdown;
let Icon = require('antd/lib/icon/index');
exports.Icon = Icon;
let Input = require('antd/lib/input/index');
exports.Input = Input;
let InputSearch = Input.Search;
exports.InputSearch = InputSearch;
let InputNumber = require('antd/lib/input-number/index');
exports.InputNumber = InputNumber;
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = InputNumber;
let Menu = require('antd/lib/menu/index');
exports.Menu = Menu;
const index_2 = require("../modal/index");
exports.Modal = index_2.default;
exports.ModalSlip = index_2.ModalSlip;
let notification = require('antd/lib/notification/index');
exports.notification = notification;
let Pagination = require('antd/lib/pagination/index');
exports.Pagination = Pagination;
let Popover = require('antd/lib/popover/index');
exports.Popover = Popover;
let Progress = require('antd/lib/progress/index');
exports.Progress = Progress;
let Select = require('antd/lib/select/index');
exports.Select = Select;
let Option = Select.Option;
exports.Option = Option;
let Spin = require('antd/lib/spin/index');
exports.Spin = Spin;
let Popconfirm = require('antd/lib/popconfirm/index');
let Switch = require('antd/lib/switch/index');
exports.Switch = Switch;
let TableReq = require('antd/lib/table/index');
let Table;
exports.Table = Table;
exports.Table = Table = TableReq;
let Tabs = require('antd/lib/tabs/index');
exports.Tabs = Tabs;
let TabPane = Tabs.TabPane;
exports.TabPane = TabPane;
let Tree = require('antd/lib/tree/index').default;
exports.Tree = Tree;
let TreeNode = Tree.TreeNode;
exports.TreeNode = TreeNode;
let message = require('antd/lib/message/index');
exports.message = message;
let TreeSelect = require('antd/lib/tree-select/index');
exports.TreeSelect = TreeSelect;
let Checkbox = require('antd/lib/checkbox/index');
exports.Checkbox = Checkbox;
const CheckboxGroup = Checkbox.Group;
exports.CheckboxGroup = CheckboxGroup;
let Radio = require('antd/lib/radio/index');
exports.Radio = Radio;
const RadioGroup = Radio.Group;
exports.RadioGroup = RadioGroup;
let Upload = require('antd/lib/upload/index').default;
exports.Upload = Upload;
});
//# sourceMappingURL=index.js.map
